// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // ⭐ دعم الويب بإضافة خيارات Firebase للويب
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc0fNZqrBCxNOGDDg7cuRk_8dluehoODI',
    appId: '1:542408928460:android:d27df1ad931b2b6664e669',
    messagingSenderId: '542408928460',
    projectId: 'hanoti-farou9',
    storageBucket: 'hanoti-farou9.firebasestorage.app',
  );

  // ⭐ إضافة خيارات Firebase للويب
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgWDZ6aLYrevG6a_9Zws9mBKMqj6HLccE',
    appId: '1:542408928460:web:73ecf7e05863b16464e669',
    messagingSenderId: '542408928460',
    projectId: 'hanoti-farou9',
    authDomain: 'hanoti-farou9.firebaseapp.com',
    storageBucket: 'hanoti-farou9.firebasestorage.app',
    measurementId:
        'G-X4HVLW572B', // ⭐ يمكنك إضافة Measurement ID من Firebase Console
  );
}
